server:
  port: 8080

spring:
  application:
    name: large-file-plupload

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  # redis 配置
  redis:
    host: 101.132.45.166
    port: 6379
    password: zyagmx1314
    database: 1
    jedis:
      pool:
        max-active: 8
        max-idle: 500
        max-wait: -1ms

plupload:
  # 最大重试次数
  maxTryCount: 5
  # 重试间隔(毫秒)
  tryInterval: 5000
  # 数据在Redis中的持有时间(秒)
  fileRedisTime: 60
  # 文件暂存路径
  tempPath:
    windows: "D:\\\\temp"
    linux: "/tmp/plupload"