# 自定义配置
init:
  name: yushen-prod
  config:
    age: ${random.int(30)}
    sex: male

# Actuator 健康检查
management:
  endpoint:
    health:
      show-details: always # /actuator/health 显示详情
  endpoints:
    web:
      exposure:
        exclude: ["heapdump"]  # 禁用某些指标
        include: ["health","info"]  # 启用某些指标