# Mysql
spring:
  datasource:
    url: jdbc:mysql://192.168.6.192:3306/commontest?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: zhengyu
    password: 123123
# JPA
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto:  create # create:创建表并销毁之前的数据 update：修改表 validate:制作校验不做修改 none：忽略
    open-in-view: false # 关闭 view
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # Mysql 数据库引擎设置为InnoDB

