server:
  port: 8989

spring:
  application:
    name: springboot-springdatajpa
  profiles:
    active: dev

# Actuator 健康检查
management:
  endpoint:
    health:
      show-details: always # /actuator/health 显示详情
  endpoints:
    web:
      exposure:
        include: ["*"]  # 启用某些指标